### ISSUE TITLE
if initLXD fails with message: network already in use

### ISSUE THREAD

**Issue by tpokorra** [tpokorra/lxd-scripts#5]
this fails:

```
lxc network delete lxdbr0
lxc network create lxdbr0 ipv6.address=none ipv4.address=10.0.4.1/24 ipv4.nat=true
```

```
Error: The network is currently in use
Error: The network already exists
```

see the solution in https://discuss.linuxcontainers.org/t/cannot-delete-lxdbr0-and-use-a-manually-created-bridge-etc-network-interfaces-once-sudo-lxd-init-has-set-up-lxdbr0-and-a-container-uses-it/750

```
lxc profile edit default
```

I removed the lines and later added them back in:

```
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
```
