### ISSUE TITLE
lxdbr0 has strange network address

### ISSUE THREAD

**Issue by tpokorra** [tpokorra/lxd-scripts#9]
```
lxc network show lxdbr0
lxc profile edit default
  # copy the content of the file

config: {}
description: Default LXD profile
devices:
  eth0:
    name: eth0
    network: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: default
used_by: []

  # comment all active lines
lxc network delete lxdbr0
lxc network create lxdbr0 ipv6.address=none ipv4.address=10.0.4.1/24 ipv4.nat=true
lxc profile edit default
 # replace with backup
```
